config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :images

  resources :devices do
    put :parse, on: :member
  end
  
  resources :inventory, only: [:index,:create]
  
  resources :tasks, except: [:new, :edit] 
  get 'tasks/:mac/finish', to: 'tasks#finish', as: :finish_task
  
  resources :sites, only: [:show] do
    resources :devices, only: [:index]
  end
  
  namespace :admin do
    resources :sites do
      resources :servers
    end
    resources :users
  end
  
  resources :push_tasks, only: [:create, :destroy]
  get 'push_tasks/:mac/finish', to: 'push_tasks#finish', as: :finish_push_task
  
  root to: 'devices#index'
  

end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id          :integer          not null, primary key
#  site_id     :integer
#  image_id    :integer
#  htmlfile    :string(255)
#  xmlfile     :string(255)
#  cpu         :string(255)
#  ram_str     :string(255)
#  make        :string(255)
#  product     :string(255)
#  serial      :string(255)
#  uuid        :string(255)
#  ip_addr     :string(255)
#  mac_address :string(255)
#  cpu_speed   :integer
#  banks       :text
#  created_at  :datetime
#  updated_at  :datetime
#  state       :string(255)
#  notes       :text
#  ram         :float
#

class Device < ActiveRecord::Base
  include HardwareExtraction
  
  mount_uploader :xmlfile, XmlUploader
  mount_uploader :htmlfile, HtmlUploader
  
  store :banks, coder: JSON
  
  belongs_to :site
  belongs_to :image
  has_many :tasks, dependent: :destroy
  
  validates :mac_address, presence: true, uniqueness: true
  validates :site_id, presence: true
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ['Site','Serial','Model','CPU','Speed','RAM Total','RAM Type','Bank0','Bank1','Bank2','Bank3']
      order(:product).includes(:site).each do |device|
        row = [device.site.name]
        row += device.attributes.values_at('serial','product','cpu','cpu_speed','ram')
        row << device.fetch_banks(['0','desc'])
        4.times do |i|
          # row << device.banks[i.to_s]['size'] unless device.banks[i.to_s].nil?
          unless device.banks[i.to_s].nil?
            if device.banks[i.to_s] == "empty"
              row << "empty"
            else
              row << device.banks[i.to_s]['size']
            end
          end
        end
        csv << row
      end
    end
  end
  
  def active_task?
    !!tasks.where(state: 'active').any?
  end
  
  def product
    super || "unknown"
  end
  
  #TODO: Best name that falls back to dev-{device_id}
  
  concerning :MacAddressing do
    def mac_address=(str)
      super(str.downcase.gsub(/\:/, ''))
    end
  
    def mac_address
      super.scan(/\w{2}/).join(':').upcase if super
    end
  
    def pxe_mac
      "01-" << mac_address.scan(/\w{2}/).join('-').downcase
    end
  end
  
  def best_name
    if serial && !serial.blank?
      serial
    elsif mac_address && mac_address != "00"*6
      mac_address
    else
      uuid
    end
  end
  
  def has_image?
    image_id.present?
  end
  
  # guards against nils
  def fetch_banks(keys = [])
    keys.inject(self.banks){|banks, key| banks && banks[key] }
  end
  
  state_machine :state, initial: :active do
    event :retire do
      transition :active => :retired
    end
    event :unretire do
      transition :retired => :active
    end
  end
  
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_device, except: [:index, :new, :create]
  
  
  # GET /devices
  # GET /devices.json
  def index
    if params[:site_id].present?
      @site = Site.find(params[:site_id])
      @device_count = @site.devices.count
      @devices = @site.devices.order(created_at: :desc).page(params[:page]).per(50)
    else
      @device_count = Device.count
      @devices = Device.order(created_at: :desc).page(params[:page]).per(50)
    end
    
    respond_to do |format|
      format.html
      format.csv do
        if @site
          send_data(@site.devices.to_csv, filename: csv_filename)
        else
          send_data(Device.to_csv, filename: csv_filename)
        end
      end
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @tasks = @device.tasks.order(created_at: :desc)
    @image_map = Image.order(:name).pluck(:name, :id)
    @site_map = Site.all.pluck(:name, :id)
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)
    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render action: 'show', status: :created, location: @device }
        format.xml { render text: "Success" }
      else
        format.html { render action: 'new' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
        format.xml { render xml: @devise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
  
  def parse
    @device.extract_from_xml!
    @device.save
    redirect_to @device
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_device
    @device = Device.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def device_params
    params.require(:device).permit(:mac_address, :site_id, :image_id, :xmlfile, :htmlfile, :notes)
  end
  
  def csv_filename
    name = "devices"
    name << "_#{@site.abbr.downcase}" if @site.present?
    name << "_#{Time.now.to_s(:number)}"
    name << ".csv"
    name
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
  
  def link_to_cancel(task)
    link_to 'cancel', task, {method: :delete, confirm: 'Cancel this task?', class: 'tiny alert button'}
  end
  
end

app/views/devices/_create_task.html.erb
<%= form_for Task.new do |f| %>
  <%= f.hidden_field :device_id, {value: device_id} %>
  <%= f.hidden_field :job, {value: job} %>
  <%= f.submit job.titleize, class: 'expand button' %>
<% end %>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/_list.html.erb
<div class="row">
  <div class="small-12 columns">
    <table>
      <thead>
        <tr>
          <th>Site</th>
          <th>Model</th>
          <th>Serial</th>
          <th>Notes</th>
          <th>Mac Address</th>
          <th>Image?</th>
          <%#TODO: add RAM %>
        </tr>
      </thead>

      <tbody>
        <% devices.each do |device| %>
          <tr class="clickable" href="<%= device_path(device) %>">
            <td><%= device.site.abbr.upcase %></td>
            <td><%= device.product.truncate(20) %></td>
            <td><%= device.best_name %></td>
            <td><%= device.notes.try(:truncate, 30) %></td>
            <td><%= device.mac_address %></td>
            <td>
              <% if device.image_id.present? %>
              <i class="fa fa-check-circle"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <% if @site.present? %>
    <h2><%= @site.name %></h2>
    <% else %>
    <h2>All devices</h2>
    <% end %>
    
    <h4 class="subheader"><%= @device_count %> Total</h4>
  </div>
</div>



<div class="row">
  <div class="medium-10 columns">
    
    <%= render partial: 'list', locals: { devices: @devices } %>
    
    <div class="row">
      <div class="small-12 columns">
        <%= paginate @devices %>
      </div>
    </div>
    
  </div>
  <div class="medium-2 columns">
    <p><%= link_to 'Download CSV', params.merge(format: :csv) %></p>
    <%= render 'sites/nav' %>
  </div>
</div>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/new.xml.erb
<%= form_authenticity_token %>

app/views/devices/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <h3><%= @device.best_name %></h3>
    <div class="meta">
      <%= link_to @device.site.name, site_devices_path(@device.site) %> | 
      <%= @device.created_at.strftime('%b %e, %Y %l:%m%p ') %>
    </div>
    <hr>
  </div>
</div>
  
<div class="row">
  <div class="medium-3 columns">
    <div class="panel">
      <%= form_for @device do |f| %>
        <%= f.label :site_id do %>
          Site
          <%= f.select :site_id, @site_map, include_blank: 'none' %>
        <% end %>
        <%= f.label :image_id do %>
          Image
          <%= f.select :image_id, @image_map, include_blank: 'none' %>
        <% end %>
        <%= f.submit 'update', class: 'tiny button' %>
      <% end %>
    </div>
    
    <ul class="side-nav">
      <% if @device.htmlfile.present? %>
      <li class="divider"></li>
      <li><%= link_to 'Populate from XML', parse_device_path(@device), method: :put %></li>
      <li><%= link_to 'View raw data', @device.htmlfile.url %></li>
      <% end %>
      <li class="divider"></li>
      <li><%= link_to 'Delete', @device, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
    
    <hr>
    

    
  </div>
    
  <div class="medium-6 columns">
    
    <table>
      <tr>
        <td>Manufacturer</td>
        <td><%= @device.make %></td>
      </tr>
      <tr>
        <td>Product</td>
        <td><%= @device.product %></td>
      </tr>
      <tr>
        <td>RAM</td>
        <td><%= @device.ram %></td>
      </tr>
      <tr>
        <td>CPU</td>
        <td>
          <%= @device.cpu %> 
          <%= @device.cpu_speed %> Mhz
        </td>
      </tr>
      <tr>
        <td>Mac Address</td>
        <td><%= @device.mac_address %></td>
      </tr>
      <tr>
        <td>UUID</td>
        <td><%= @device.uuid %></td>
      </tr>
    </table>
    
    
    <h4>RAM</h4>
    <table>
      <tr>
        <% @device.banks.size.times do |i| %>
        <th><%= i %></th>
        <% end %>
      </tr>
      <tr>
        <% @device.banks.each do |pos, bank| %>
        <td><%= bank['size'] || "empty" %></td>
        <% end %>
      </tr>
    </table>
    
    <h4>Notes</h4>
    <%= form_for @device do |f| %>
      <div class="field">
        <%= f.text_area :notes, placeholder: 'Notes' %>
      </div>
    <%= f.submit 'update notes', class: 'tiny button' %>
    <% end %>
    
    
  </div>
  
  <div class="medium-3 columns">
    
    <% if @device.image.nil? %>
    
      <div class="panel">
        You must set the image for this device before
        you can start a task.
      </div>
    
    <% elsif @device.active_task? %>
    
      <div class="panel">
        <p>Currently waiting for <%= @device.tasks.find_by(state: 'active').job %> to complete.</p>
      </div>
    
    <% else %>
    
      <%= render partial: 'create_task', locals: {device_id: @device.id, job: 'deploy'} %>
      <%= render partial: 'create_task', locals: {device_id: @device.id, job: 'upload'} %>
    
    <% end %>
    
    <h4>Task history</h4>
    
    <% if @tasks.any? %>
    
    <ul class="task-history">
      <% @tasks.each do |task| %>
      <li class="task">
        <b class="task-job"><%= task.job %></b><br>
        <span class="task-time"><%= task.updated_at.to_s(:short) %></span>
        <span class="task-state task-<%= task.state %>"><%= task.state %></span>
        <% if task.active? %>
        <span class="task-cancel">
          <%= link_to_cancel(task) %>
        </span>
        <% end %>
      </li>
      <% end %>
    </ul>
    
    <% else %>
    
    <p>No task history yet.</p>
    
    <% end %>
    
  </div>
    
</div>