config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :images

  resources :devices do
    put :parse, on: :member
  end
  
  resources :inventory, only: [:index,:create]
  
  resources :tasks, except: [:new, :edit] 
  get 'tasks/:mac/finish', to: 'tasks#finish', as: :finish_task
  
  resources :sites, only: [:show] do
    resources :devices, only: [:index]
  end
  
  namespace :admin do
    resources :sites do
      resources :servers
    end
    resources :users
  end
  
  resources :push_tasks, only: [:create, :destroy]
  get 'push_tasks/:mac/finish', to: 'push_tasks#finish', as: :finish_push_task
  
  root to: 'devices#index'
  

end

app/models/server.rb
class Server < ActiveRecord::Base
  belongs_to :site
  enum role: { storage: 0, pxe: 1 }
end

app/controllers/admin/servers_controller.rb
class Admin::ServersController < AdminController
  before_action :set_site
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = @site.servers
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = @site.servers.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = @site.servers.new(server_params.merge({used_at: (Time.now - 1.day)}))

    respond_to do |format|
      if @server.save
        format.html { redirect_to [:admin, @site], notice: 'Server was successfully created.' }
        format.json { render action: 'show', status: :created, location: [:admin, @site] }
      else
        format.html { render action: 'new' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to [:admin, @site], notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, @site] }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:site_id])
    end
    
    def set_server
      @server = @site.servers.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:ip_addr, :role)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/admin/servers/_form.html.erb
<%= form_for([:admin, @site, @server]) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :ip_addr %><br>
    <%= f.text_field :ip_addr %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, ['storage', 'pxe'] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_site_servers_path(@site) %>

app/views/admin/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>Ip addr</th>
      <th colspan="2">Ops</th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.role %></td>
        <td><%= server.ip_addr %></td>
        <td><%= link_to 'Edit', edit_admin_site_server_path(@site, server) %></td>
        <td><%= link_to 'Destroy', [:admin, @site, server], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_admin_site_server_path %>

app/views/admin/servers/new.html.erb
<div class="row">
  <div class="medium-8 columns">
    <h3>New <%= @site.abbr.upcase %> server</h3>
    <hr>
    <%= render 'form' %>
    <%= link_to 'Back', admin_site_servers_path(@site) %>
  </div>
</div>

app/views/admin/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site:</strong>
  <%= @server.site %>
</p>

<p>
  <strong>Ip addr:</strong>
  <%= @server.ip_addr %>
</p>

<p>
  <strong>Role:</strong>
  <%= @server.role %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>