config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :images

  resources :devices do
    put :parse, on: :member
  end
  
  resources :inventory, only: [:index,:create]
  
  resources :tasks, except: [:new, :edit] 
  get 'tasks/:mac/finish', to: 'tasks#finish', as: :finish_task
  
  resources :sites, only: [:show] do
    resources :devices, only: [:index]
  end
  
  namespace :admin do
    resources :sites do
      resources :servers
    end
    resources :users
  end
  
  resources :push_tasks, only: [:create, :destroy]
  get 'push_tasks/:mac/finish', to: 'push_tasks#finish', as: :finish_push_task
  
  root to: 'devices#index'
  

end

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="fixed contain-to-grid">
      <nav class="top-bar" data-topbar data-options="is_hover: false">
        <ul class="title-area">
          <li class="name">
            <h1><a href="/">Tory</a></h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
        </ul>
        <section class="top-bar-section">
          <ul class="left">
            <li><%= link_to 'Devices', devices_path %></li>
            <li><%= link_to 'Tasks', tasks_path %></li>
            <li><%= link_to 'Images', images_path %></li>
            <li><%= link_to 'Admin', admin_sites_path %></li>
          </ul>
          
          <ul class="right">
            <li><%= link_to 'Sign-out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tory</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if flash.any? %>
  <div class="messages">
    <% flash.each do |k,v| %>
    <div class="alert-box <%= k %>">
      <%= v %>
    </div>
    <% end %>
  </div>
  <% end %>
  
  <%= render 'layouts/nav' %>

  <div class="content">
    <div class="row">
      <div class="medium-3 columns">
        <ul class="side-nav">
          <li><%= link_to 'Manage Sites', admin_sites_path %></li>
          <li><%= link_to 'Manage Users', admin_users_path %></li>
        </ul>
      </div>
      <div class="medium-9 columns">
        <%= yield %>
      </div>
    </div>
  </div>
  

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tory</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <% if flash.any? %>
  <div class="messages">
    <% flash.each do |k,v| %>
    <div class="alert-box <%= k %>">
      <%= v %>
    </div>
    <% end %>
  </div>
  <% end %>
  
  <div class="row">
    <div class="large-12 columns">
      <div class="fixed contain-to-grid">
        <nav class="top-bar" data-topbar data-options="is_hover: false">
          <ul class="title-area">
            <li class="name">
              <h1><a href="/">Tory</a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
          </ul>
          <section class="top-bar-section">
            <ul class="left">
              <li><%= link_to 'Devices', devices_path %></li>
              <li><%= link_to 'Images', images_path %></li>
              <li><%= link_to 'Sites', sites_path %></li>
              <li><%= link_to 'Tasks', tasks_path %></li>
            </ul>
            
            <ul class="right">
              <li><%= link_to 'Sign-out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </section>
        </nav>
      </div>
    </div>
  </div>

  <%= yield %>

</body>
</html>