config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :images

  resources :devices do
    put :parse, on: :member
  end
  
  resources :inventory, only: [:index,:create]
  
  resources :tasks, except: [:new, :edit] 
  get 'tasks/:mac/finish', to: 'tasks#finish', as: :finish_task
  
  resources :sites, only: [:show] do
    resources :devices, only: [:index]
  end
  
  namespace :admin do
    resources :sites do
      resources :servers
    end
    resources :users
  end
  
  resources :push_tasks, only: [:create, :destroy]
  get 'push_tasks/:mac/finish', to: 'push_tasks#finish', as: :finish_push_task
  
  root to: 'devices#index'
  

end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  abbr       :string(255)
#  pxe        :string(255)
#  storage    :string(255)
#  code       :integer
#  created_at :datetime
#  updated_at :datetime
#

class Site < ActiveRecord::Base
  has_many :devices
  has_many :servers
  
  def storage_servers
    servers.where(role: 0)
  end
  
  def pxe_servers
    servers.where(role: 1)
  end
  
  def next_storage
    nxt = storage_servers.order(:used_at).first
    if nxt.nil?
      storage
    else
      nxt.touch(:used_at)
      nxt
    end
  end
end

# def next_server(site)
#   nxt = site.storage_servers.order(:used_at).first
#   nxt.update(used_at: Time.now)
#   nxt
# end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < AdminController
  before_action :load_site, except: [:index, :new, :create]
  def index
    @sites = Site.order(:code).includes(:servers)
  end
  
  def new
    @site = Site.new
  end
  
  def show
  end
  
  def edit
  end
  
  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to admin_sites_path, notice: 'Site created.'
    else
      render action: 'new'
    end
  end
  
  def update
    if @site.update(site_params)
      redirect_to admin_sites_path, notice: 'Site updated.'
    else
      render action: 'edit'
    end
  end
  
  private
  
  def load_site
    @site = Site.find(params[:id])
  end
  
  def site_params
    params.require(:site).permit(:name, :abbr, :pxe, :storage, :code)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_site, except: [:index, :new, :create]
  def index
    @sites = Site.all
  end
  
  def show
    @devices = @site.devices.order(created_at: :desc).limit(5)
    @product_counts = @site.devices.group(:product).order('count_product desc').count(:product)
  end
  
  def new
    @site = Site.new
  end
  
  def edit
  end
  
  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to sites_path, notice: 'Site created.'
    else
      render action: 'new'
    end
  end
  
  def update
    if @site.update(site_params)
      redirect_to sites_path, notice: 'Site updated.'
    else
      render action: 'edit'
    end
  end
  
  private
  
  def load_site
    @site = Site.find(params[:id])
  end
  
  def site_params
    params.require(:site).permit(:name, :abbr, :pxe, :storage, :code)
  end
end

app/views/admin/sites/_form.html.erb
<%= form_for [:admin, @site] do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :abbr, 'Abbreviation' %>
    <%= f.text_field :abbr %>
  </div>
  
  <div class="field">
    <%= f.label :pxe, 'PXE server address' %>
    <%= f.text_field :pxe %>
  </div>
  
  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/admin/sites/edit.html.erb
<div class="row">
  <div class="medium-8 columns">
    <h3>Editing <%= @site.name %></h3>
    <hr>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/sites/index.html.erb
<div class="row">
  <div class="medium12 columns">
    <h3>Listing Sites</h3>
    <p><%= link_to 'Add site', new_admin_site_path %></p>
    <table>
      <thead>
        <tr>
          <th>Code</th>
          <th>Abbr</th>
          <th>Name</th>
          <th>PXE</th>
          <th>Storage</th>
          <th></th>
        </tr>
      </thead>
      
      <tbody>
        <% @sites.each do |site| %>
          <tr>
            <td><%= site.code %></td>
            <td><%= site.abbr.upcase %></td>
            <td><%= site.name %></td>
            <td><%= site.pxe %></td>
            <td><%= site.storage_servers.map(&:ip_addr).join(', ') %></td>
            <td>
              <%= link_to 'Edit', edit_admin_site_path(site) %> | 
              <%= link_to 'Servers', admin_site_servers_path(site) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/sites/new.html.erb
<%= render 'form' %>

app/views/admin/sites/show.html.erb
<h3><%= @site.name %></h3>

<h5>Servers</h5>

<table>
  <% @site.servers.each do |server| %>
    <tr>
      <td><%= server.ip_addr %></td>
      <td><%= server.role %></td>
      <td><%= link_to 'Edit', edit_admin_site_server_path(@site, server) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'New Server', new_admin_site_server_path(@site) %></p>